### ISSUE TITLE
Milestone 4 Plans and Discussion

### ISSUE THREAD

**Issue by liannah** [UBC-MDS/rbccovideda#48]
Feb 1 
- list Milestone 4 tasks and assign to each group member
- every group member should update the issue status of their assigned tasks in Github project
- next checkpoint meeting :  Feb 4 1900
- Canvas Submission - Lianna

Tasks for R package:
- [ ] Integrate Github actions (Vadim)
- [ ] Create a package wide documentation (Vanessa)
- [ ] Package review request (John)
- [ ] License discussion (John, Lianna, Vadim, Vanessa)
- [ ] Final check and submission (Lianna)
- [ ] Fix warnings (John)
